### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by ogzhnoksuz** [mralimac/Steam-Alt-Account-Lookup#1]
Warning: file_get_contents(http://api.steampowered.com/IPlayerService/IsPlayingSharedGame/v0001/?key=&steamid=76561198142449806&appid_playing=&format=json): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in /home/csgohera/public_html/wow/profilechecker.html on line 147

**Comment by mralimac** [comment]
Did you specify an API key?
You need to fill in the value on [line 18 of profilechecker.html](https://github.com/mralimac/Steam-Alt-Account-Lookup/blob/master/profilechecker.html#L18) with a valid steam API key
Get a key from [here](http://steamcommunity.com/dev/apikey)

**Comment by ogzhnoksuz** [comment]
I write api key but again same error

**Comment by ogzhnoksuz** [comment]
146 $altcheckurl = "http://api.steampowered.com/IPlayerService/IsPlayingSharedGame/v0001/?key=".$key."&steamid=".$communityid."&appid_playing=".$appid."&format=json";
			147$jsonaltcheck = file_get_contents($altcheckurl);
			148$schemaaltcheck = json_decode($jsonaltcheck, true);
			149$altcheckresponse = $schemaaltcheck['response']['lender_steamid'];

**Comment by mralimac** [comment]
Is fopen enabled in your servers PHP ini file?
Make sure the line "allow_url_fopen" is set to true
You could also let me see your phpinfo() to make its not disabled

To make a php-info page. Just make a new blank php page and write the following in it:
<?php phpinfo(); ?>

**Comment by ogzhnoksuz** [comment]
http://www.csgohera.com/wow/

**Comment by mralimac** [comment]
This doesn't tell me much. Have you changed your php.ini file?

**Comment by ogzhnoksuz** [comment]
http://csgohera.com/wow/as.php
"allow_url_fopen" is true

**Comment by mralimac** [comment]
Hmm. After reviewing my code, I realise its a bit outdated and broken. I'll rework it and release a newer version later when I have time. 
I'm not sure what your problem is unfortunately, I'll research it more to try and find a solution

I just tested my script on your website and my checker still works. Its just not fully operational. But it can still tell if an account is using an alt or not.
